### ISSUE TITLE
STM32 CAN  Function support 

### ISSUE THREAD

**Issue by skylin008** [MikroElektronika/mikrosdk_v2#7]
***Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skylin008** [comment]
Thanks @StrahinjaJacimovic

**Comment by StrahinjaJacimovic** [comment]
Hello @skylin008 

CAN has been added for all architectures. Best regards and have fun using it.

Closing the issue now.
